// packages/web/src/app/layout.tsx
import type { Metadata } from 'next';
import { Inter } from 'next/font/google';
import Script from 'next/script';

import './globals.css';
import { Navbar } from '@/components/Navbar';
import { Footer } from '@/components/Footer';
import { ToastProvider } from '@/context/ToastContext';

const inter = Inter({
  subsets: ['latin'],
  display: 'swap',
});

// --- THIS METADATA OBJECT IS NOW CORRECT ---
export const metadata: Metadata = {
  // Sets the root domain for all pages
  metadataBase: new URL('https://use.soap.fyi'),

  title: 'Soap | Public Polling',
  description: 'See what people really think. Soap provides live, public polling data and sentiment analysis on leading political figures. Your vote, your voice.',
  icons: {
    icon: '/favicon.ico',
  },

  // Sets the canonical URL for the homepage ('/') relative to metadataBase
  alternates: {
    canonical: '/',
  },
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" className={inter.className}>
      {/* The <head> tag is automatically generated by Next.js from the metadata object. */}
      <body>
        {/* Google Analytics script should be placed directly in the body */}
        <Script
          async
          src="https://www.googletagmanager.com/gtag/js?id=G-MCWMGMG51E"
          strategy="afterInteractive"
        />
        <Script id="google-analytics">
          {`
            window.dataLayer = window.dataLayer || [];
            function gtag(){dataLayer.push(arguments);}
            gtag('js', new Date());

            gtag('config', 'G-MCWMGMG51E');
          `}
        </Script>
        
        <ToastProvider>
          <Navbar />
          <main>{children}</main>
          <Footer />
        </ToastProvider>
      </body>
    </html>
  );
}